name: CIT Crossdock

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  crossdock:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        steps:
        - name: crossdock
          cmd: bash scripts/build-crossdock.sh
        - name: crossdock-otel
          cmd: make build-crossdock crossdock-otel
    name: ${{ matrix.steps.name }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Fetch git tags
      run: |
        git fetch --prune --unshallow --tags

    - uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Export BRANCH variable
      uses: ./.github/actions/setup-branch

    - name: Install tools
      run: make install-ci

    - name: Build, test, and publish ${{ matrix.steps.name }} image
      run: ${{ matrix.steps.cmd }}
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}

    - name: Output crossdock logs
      run: make crossdock-logs
      if: ${{ failure() }}
