receivers:
  otlp:
    protocols:
      http:
      grpc:

processors:

exporters:
  file:
    path: ./filename.json
  logging:

service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors: []
      exporters:
        - file
        - logging
