PUT http://172.17.0.4:8080/collect/rawdata/f760b009-f5f5-4ff2-a658-1135165879d7
Content-Type: multipart/form-data; boundary=End

--End

Content-Disposition: form-data; name="file"; filename="fname"
Content-Type: text/plain

< ./fname

--End--

